version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment
  payment:
    build:
      context: .
      dockerfile: docker/build.dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_DRIVER: ${DB_DRIVER:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-payment}
      DB_PORT: ${DB_PORT:-5432}
